version: '2'
services:
  app:
    build: . # "." pour signier le Dockerfile
    image: flask-redis:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 80:80
  redis:
    image: redis:4.0.11-alpine
#     networks:
#       - backend
#     volumes:
#       - dbdata:/data

# networks:
#   backend: # création d'un réseau backend (optionnel)
#   frontend: # création d'un réseau frontend (optionnel)

# volumes:
#   dbdata: # création du volume dbdata
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/srv/redis'
